# Generated by Django 4.2.19 on 2025-03-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobtrentds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTrentds',
            new_name='JobTrends',
        ),
    ]
