# Generated by Django 4.2.19 on 2025-03-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_jobtrentds_jobtrends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationLevel', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(blank=True, max_length=50, null=True)),
                ('graduationDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
