# Generated by Django 4.2.19 on 2025-03-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='user',
            new_name='account',
        ),
    ]
