# Generated by Django 4.2.19 on 2025-03-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
