# Generated by Django 4.2.19 on 2025-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='datePosted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
