# Generated by Django 4.2.19 on 2025-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_jobposting_dateposted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='jobURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
