# Generated by Django 4.2.19 on 2025-04-04 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_jobposting_description_alter_jobposting_joburl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=15),
        ),
    ]
