# Generated by Django 4.2.19 on 2025-04-08 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_account_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=15),
        ),
    ]
