# Generated by Django 4.2.19 on 2025-04-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_account_certifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='skills',
            new_name='userSkills',
        ),
    ]
