# Generated by Django 4.2.19 on 2025-04-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_skills_account_userskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userSkills',
            new_name='skills',
        ),
    ]
