# Generated by Django 4.2.19 on 2025-04-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_userskills_account_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='skills',
        ),
    ]
