# Generated by Django 4.2.19 on 2025-04-09 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_account_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=15),
        ),
    ]
