# Generated by Django 4.2.19 on 2025-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_account_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='skills',
        ),
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='account', to='api.commonskills'),
        ),
    ]
