# Generated by Django 4.2.19 on 2025-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_commonskills_remove_account_skills_account_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='job_posting', to='api.commonskills'),
        ),
    ]
