# Generated by Django 4.2.19 on 2025-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_commonjobpreferences_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='headline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pronouns',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
