# Generated by Django 4.2.19 on 2025-04-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_account_headline_account_pronouns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='education',
        ),
        migrations.RemoveField(
            model_name='account',
            name='experience',
        ),
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.education'),
        ),
        migrations.AddField(
            model_name='account',
            name='experience',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.experience'),
        ),
    ]
