# Generated by Django 4.2.19 on 2025-04-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_account_education_remove_account_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonJobPreferences',
            new_name='CommonPreferences',
        ),
        migrations.RenameModel(
            old_name='JobTrends',
            new_name='JobTrend',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='location',
            new_name='hometown',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountImage',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='jobPrefs',
            new_name='preferences',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='educationLevel',
            new_name='grade',
        ),
    ]
