# Generated by Django 4.2.19 on 2025-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_resumeparser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='datePosted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='jobURL',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
