# Generated by Django 4.2.19 on 2025-09-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_jobposting_dateposted_alter_jobposting_joburl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountStatus',
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='account',
            name='summary',
        ),
    ]
