# Generated by Django 4.2.19 on 2025-09-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_account_accountstatus_remove_account_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='chatHistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chatbothistory'),
        ),
    ]
