# Generated by Django 4.2.19 on 2025-09-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_chatbothistory_account_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='chatHistory',
        ),
        migrations.AddField(
            model_name='chatbothistory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='chatbothistory',
            name='specificJob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobposting'),
        ),
    ]
