# Generated by Django 4.2.19 on 2025-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_account_chathistory_chatbothistory_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('numberOfJobs', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeParser',
        ),
    ]
