# Generated by Django 4.2.19 on 2025-09-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_jobstatistics_delete_resumeparser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbothistory',
            name='time',
        ),
        migrations.AddField(
            model_name='chatbothistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
