# Generated by Django 4.2.19 on 2025-10-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_chatbothistory_time_chatbothistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='education',
        ),
        migrations.RemoveField(
            model_name='account',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AddField(
            model_name='education',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
