# Generated by Django 4.2.19 on 2025-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
