# Generated by Django 4.2.19 on 2025-10-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_education_gpa_alter_education_graduationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbothistory',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
