# Generated by Django 4.2.19 on 2025-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_chatbothistory_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='minimumRequirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
