# Generated by Django 4.2.19 on 2025-10-27 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_jobposting_minimumrequirements_jobposting_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='description',
            new_name='fullDescription',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='minimumRequirements',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='summary',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='degreeType',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employmentType',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experienceLevel',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='fieldOfStudy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='locationType',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='shortDescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_posting', to='api.commonskills'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='datePosted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, default=list),
        ),
    ]
