# Generated by Django 4.2.19 on 2025-10-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_description_jobposting_fulldescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='fieldOfStudy',
            new_name='careerArea',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employmentType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experienceLevel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='locationType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
