# Generated by Django 4.2.19 on 2025-10-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_fieldofstudy_jobposting_careerarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDegrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonEmploymentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonExperienceLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonWorkModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CommonPreferences',
            new_name='CommonCareers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='careerArea',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='degreeType',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='employmentType',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='experienceLevel',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='locationType',
        ),
        migrations.AddField(
            model_name='account',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.commoncareers'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commoncareers'),
        ),
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.commonskills'),
        ),
        migrations.AlterField(
            model_name='education',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.account'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.account'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='shortDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commonskills'),
        ),
        migrations.AddField(
            model_name='account',
            name='employmentTypes',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.commonemploymenttypes'),
        ),
        migrations.AddField(
            model_name='account',
            name='experienceLevels',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.commonexperiencelevels'),
        ),
        migrations.AddField(
            model_name='account',
            name='workModels',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.commonworkmodels'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commondegrees'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employmentTypes',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commonemploymenttypes'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experienceLevels',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commonexperiencelevels'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='workModels',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='api.commonworkmodels'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='api.commondegrees'),
        ),
    ]
