# Generated by Django 4.2.19 on 2025-10-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_commondegrees_commonemploymenttypes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='fullDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='shortDescription',
            new_name='summary',
        ),
    ]
