# Generated by Django 4.2.19 on 2025-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_fulldescription_jobposting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emailVerification',
            field=models.BooleanField(default=False),
        ),
    ]
