# Generated by Django 4.2.19 on 2025-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_account_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='logoURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
