# Generated by Django 4.2.19 on 2025-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_jobposting_requirements_jobposting_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notify_by_email',
            field=models.BooleanField(default=True, help_text='If false, the user will not receive email notifications.'),
        ),
    ]
