# Generated by Django 4.2.19 on 2025-11-06 05:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_jobposting_requirements_jobposting_logourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=api.models.userFilesPath),
        ),
    ]
