# Generated by Django 4.2.19 on 2025-11-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_account_notify_by_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='emailVerification',
        ),
    ]
