# Generated by Django 4.2.19 on 2025-11-08 06:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_account_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=api.models.userFilesPath),
        ),
    ]
