# Generated by Django 4.2.19 on 2025-11-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_account_resume'),
    ]

    operations = [
    ]
