# Generated by Django 4.2.19 on 2025-11-08 20:40

import api.models
from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20251108_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=django_encrypted_filefield.fields.EncryptedFileField(blank=True, null=True, upload_to=api.models.userFilesPath),
        ),
    ]
