# Generated by Django 4.2.19 on 2025-11-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_account_emailverification 2'),
        ('api', '0052_alter_account_resume'),
    ]

    operations = [
    ]
